CREATE DATABASE SP_MEDICAL;
GO

USE SP_MEDICAL;
GO

CREATE TABLE CLINICA(
idClinica TINYINT PRIMARY KEY IDENTITY,
nomeClinica VARCHAR(20) NOT NULL UNIQUE,
endClinica VARCHAR(50) NOT NULL UNIQUE,
horarioAbertura CHAR(5) NOT NULL,
horarioFechamento CHAR(5) NOT NULL,
razaoSocial VARCHAR(20) NOT NULL
);
GO

CREATE TABLE ESPECIALIDADE(
idEspecialidade TINYINT PRIMARY KEY IDENTITY,
nomeEspecialidade VARCHAR(45) NOT NULL,
);
GO

CREATE TABLE TIPOUSUARIO(
idTipoUsuario TINYINT PRIMARY KEY IDENTITY,
nomeTipoUsuario VARCHAR(15) NOT NULL
);
GO

CREATE TABLE USUARIO(
idUsuario INT PRIMARY KEY IDENTITY,
idTipoUsuario TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario),
nomeUsuario VARCHAR(40) NOT NULL,
emailUsuario VARCHAR(90) NOT NULL UNIQUE,
senhaUsuario VARCHAR(8) NOT NULL
);
GO

CREATE TABLE PACIENTE(
idPaciente TINYINT PRIMARY KEY IDENTITY,
idUsuario INT FOREIGN KEY REFERENCES USUARIO(idUsuario),
dataNascimento CHAR(10) NOT NULL,
telefonePaciente CHAR(13) UNIQUE,
rgPaciente CHAR(10) NOT NULL UNIQUE,
cpfPaciente CHAR(11) NOT NULL UNIQUE,
endPaciente VARCHAR(100) NOT NULL,
);
GO

CREATE TABLE MEDICO(
idMedico TINYINT PRIMARY KEY IDENTITY,
idUsuario INT FOREIGN KEY REFERENCES USUARIO(idUsuario),
idClinica TINYINT FOREIGN KEY REFERENCES CLINICA(idClinica),
idEspecialidade TINYINT FOREIGN KEY REFERENCES ESPECIALIDADE(idEspecialidade),
cnpjMedico VARCHAR(20) NOT NULL,
razaoSocial VARCHAR(20) NOT NULL,
endClinica VARCHAR(50) NOT NULL
);
GO

CREATE TABLE SITUACAOCONSULTA(
idSituacaoConsulta SMALLINT PRIMARY KEY IDENTITY,
nomeSituacao VARCHAR(10)
);
GO

CREATE TABLE CONSULTA(
idConsulta TINYINT PRIMARY KEY IDENTITY,
idMedico TINYINT FOREIGN KEY REFERENCES MEDICO(idMedico),
idPaciente TINYINT FOREIGN KEY REFERENCES PACIENTE(idPaciente),
dataConsulta DATETIME NOT NULL,
descricao VARCHAR(500),
idSituacaoConsulta SMALLINT FOREIGN KEY REFERENCES SITUACAOCONSULTA(idSituacaoConsulta)
);
GO

drop table USUARIO